### PR TITLE
Fix copy file error on macos

### PR DESCRIPTION
**Pull request by cristianonicolai**
Fixes https://github.com/ansible/ansible-development-environment/issues/61

### CODE REVIEW

**Review by priyamsahoo — APPROVED** [review]

**Comment by cidrblock** [comment]
@cristianonicolai This looks like it's going to copy all files, not just ones that are git tracked...  We'll need to talk about a different approach. We don't need _everything_ copied over for the collection

**Comment by cristianonicolai** [comment]
@cidrblock thanks for the feedback, I adjusted the code so it only copies tracked files now, is that ok?

**Comment by cidrblock** [comment]
I'm not a fan of the new dependency... Could we just run subprocess out to git and grab it's output for the list rather than pulling in a new dep? and then hand that list over to copy?

**Comment by ssbarnea** [comment]
@cidrblock I agree with you, but I will merge it now in order to release the tech-preview. Note to drop gitpython as a dependency, added as https://github.com/ansible/ansible-development-environment/issues/67

That only to allow other changes to go on. IMHO, fixing the macos incompatibility is more urgent than avoiding gitpython.

**Review by ssbarnea — APPROVED** [review]

**Comment by cristianonicolai** [comment]
Closing this one, will be fixed on https://github.com/ansible/ansible-development-environment/pull/69

**Pull request closed without merging**
